# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZXu6jALsh3xJQ463gHzShJ36ick3bAZj
"""

import streamlit as st
from ultralytics import YOLO
import cv2
from PIL import Image
import numpy as np

st.title("🔍 Real-Time Object Detection using YOLOv8")

st.write("Upload an image to detect objects using a pretrained YOLOv8 model.")

# Load model
model = YOLO('yolov8n.pt')

# File uploader
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Read image
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image', use_container_width=True)

    # Convert to array
    img_array = np.array(image)

    # Perform detection
    results = model(img_array)

    # Annotate image
    annotated_frame = results[0].plot()

    st.image(annotated_frame, caption="Detected Objects", use_container_width=True)